c::::::::::::::
c	lpyr.f77
c::::::::::::::
      INTEGER FUNCTION LPYR(YEAR)
C
C FUNCTION LPYR DETERMINES IF YEAR
C IS A LEAP YEAR.
C
C THIS FUNCTION USES THE INTRINSIC
C FUNCTION MOD. IF YOUR MACHINE
C DOES NOT SUPPLY THIS FUNCTION,
C MAKE ONE -
C MOD(I,J) = IABS(I - (I/J)*J)
C
C
C CALLS:
C   MOD - INTRINSIC FUNTION
C
C      PROGRAMMED BY MADELEINE ZIRBES
C         SEPTEMBER 15,1980
C
C YEAR - INPUT
      INTEGER YEAR
      IF(.NOT.(MOD(YEAR,400).EQ.0))GOTO 23000
         LPYR = (1)
         RETURN
23000 CONTINUE
      IF(.NOT.(MOD(YEAR,4) .NE. 0))GOTO 23002
         LPYR = (0)
         RETURN
23002 CONTINUE
      IF(.NOT.(MOD(YEAR,100).EQ.0))GOTO 23004
         LPYR = (0)
         RETURN
23004 CONTINUE
      LPYR = (1)
      RETURN
      END
